- hosts: web
  become: yes
  tasks:
    - name: Copy build files
      copy:
        src: ./build/
        dest: /var/www/react-app/
    
    - name: Configure nginx
      copy:
        dest: /etc/nginx/sites-available/react-app
        content: |
          server {
              listen 80;
              root /var/www/react-app;
              index index.html;
              location / {
                  try_files $uri /index.html;
              }
          }

    - name: Enable site
      file:
        src: /etc/nginx/sites-available/react-app
        dest: /etc/nginx/sites-enabled/react-app
        state: link

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
