- hosts: web
  become: yes

  tasks:
    - name: Ensure rsync is installed
      package:
        name: rsync
        state: present
        
    - name: Ensure nginx html directory exists
      file:
        path: /usr/share/nginx/html
        state: directory
        mode: '0755'

    - name: Deploy React build
      synchronize:
        src: build/
        dest: /usr/share/nginx/html/
        delete: yes
        recursive: yes

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
